<?php
global $user;

function user_greeting_menu() {
    $items = array();
    $items['hello'] = array(
        'title' => "Hey Dude!",
        'page callback' => 'say_hey',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['adios'] = array(
        'title' => "See Ya Homie!",
        'page callback' => 'say_goodbye',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hey() {
    global $user;
    if(in_array('administrator', array_values($user->roles))) {
      return '<p>Hey, dude! You are an administrator</p>';
  } else if (in_array('moderator', array_values($user->roles))) {
      return '<p>Hey, dude! You are a moderator!</p>';
  } else if (in_array('vip user', array_values($user->roles))) {
      return '<p>Hey, dude! You are a VIP user!</p>';
  } else {
      return '<p>Hey, dude! You are a normal norm!</p>';
  }
}

function say_goodbye() {
    global $user;
    if(in_array('administrator', array_values($user->roles))) {
      return '<p>See you later, administrator</p>';
  } else if (in_array('moderator', array_values($user->roles))) {
      return '<p>See you later, moderator!</p>';
  } else if (in_array('vip user', array_values($user->roles))) {
      return '<p>See you later, VIP user!</p>';
  } else {
      return '<p>See you later, normal norm!</p>';
  }
}

function user_greeting_user_login() {
    $_GET['destination'] = 'hello';
}

function user_greeting_user_logout() {
    $_GET['destination'] = 'adios';
}
