<?php

function user_greeting_menu() {
    $items = array();
    $items['hello'] = array(
        'title' => "Hey Dude!",
        'page callback' => 'say_hey',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['adios_admin'] = array(
        'title' => "See Ya Homie!",
        'page callback' => 'say_goodbye_admin',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['adios_moderator'] = array(
        'title' => "See Ya Homie!",
        'page callback' => 'say_goodbye_moderator',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['adios_vip'] = array(
        'title' => "See Ya Homie!",
        'page callback' => 'say_goodbye_vip',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['adios_normal'] = array(
        'title' => "See Ya Homie!",
        'page callback' => 'say_goodbye_normal',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hey() {
    global $user;
    if(in_array('administrator', array_values($user->roles))) {
      return '<p>Hey, dude! You are an administrator</p>';
  } else if (in_array('moderator', array_values($user->roles))) {
      return '<p>Hey, dude! You are a moderator!</p>';
  } else if (in_array('vip user', array_values($user->roles))) {
      return '<p>Hey, dude! You are a VIP user!</p>';
  } else {
      return '<p>Hey, dude! You are a normal norm!</p>';
  }
}

function user_greeting_user_login() {
    $_GET['destination'] = 'hello';
}

function user_greeting_user_logout() {
    global $user;
    if (in_array('administrator', array_values($user->roles))) {
        $_GET['destination'] = 'adios_admin';
    } else if (in_array('moderator', array_values($user->roles))) {
        $_GET['destination'] = 'adios_moderator';
    } else if (in_array('vip user', array_values($user->roles))) {
        $_GET['destination'] = 'adios_vip';
    } else {
        $_GET['destination'] = 'adios_normal';
    }
}

function say_goodbye_admin() {
    return '<p>See you later, administrator</p>';
}

function say_goodbye_moderator() {
    return '<p>See you later, TodMod!</p>';
}

function say_goodbye_vip() {
    return '<p>See you later, SkipVIP!</p>';
}

function say_goodbye_normal() {
    return '<p>See you later, Normal Norm!</p>';
}
